- id: '1779201204760'
  alias: NotificationDelete
  description: ''
  triggers:
  - trigger: persistent_notification
    update_type:
    - removed
    notification_id: ''
  conditions: []
  actions:
  - sequence:
    - action: light.turn_on
      metadata: {}
      target:
        entity_id: light.openkarotz_color_1
      data:
        rgb_color:
        - 0
        - 249
        - 0
    - action: light.turn_off
      metadata: {}
      target:
        entity_id: light.openkarotz_color_2
      data: {}
  mode: single
- id: '1779201227812'
  alias: NotificationNew
  description: ''
  triggers:
  - trigger: persistent_notification
    update_type:
    - added
    notification_id: ''
  conditions: []
  actions:
  - sequence:
    - action: light.turn_on
      metadata: {}
      target:
        entity_id: light.openkarotz_color_1
      data:
        rgb_color:
        - 255
        - 38
        - 0
    - action: light.turn_off
      metadata: {}
      target:
        entity_id: light.openkarotz_color_2
      data: {}
  mode: single
