name: HACS Action

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  repository:
    runs-on: ubuntu-latest
    name: "${{ matrix.repository.category }}: ${{ matrix.repository.name }}"
    strategy:
      matrix:
        repository:
          - name: hacs/integration
            category: integration
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: HACS Action
        uses: ./
        with:
          comment: false
          category: ${{ matrix.repository.category }}
          ignore: ${{ matrix.repository.ignore }}
          repository: ${{ matrix.repository.name }}